import Testing
import Foundation

// MARK: - camelCase helper (mirrors GenerateModelSourcesTool/main.swift)
// The function lives in an executable target and cannot be imported, so we
// reproduce it here verbatim to keep the tests in sync with the source.

private func camelCase(_ name: String) -> String {
    name
        .components(separatedBy: CharacterSet.alphanumerics.inverted)
        .filter { !$0.isEmpty }
        .enumerated()
        .map { $0.offset == 0 ? $0.element.lowercased() : $0.element.capitalized }
        .joined()
}

// MARK: - Tests

@Suite("GenerateModelSourcesTool – camelCase")
struct CamelCaseTests {

    @Test("Single word is lowercased")
    func singleWord() {
        #expect(camelCase("Llama") == "llama")
    }

    @Test("Hyphen-separated words become camelCase")
    func hyphenSeparated() {
        #expect(camelCase("Llama-3.2-3B-Instruct") == "llama323BInstruct")
    }

    @Test("Dot-separated words become camelCase")
    func dotSeparated() {
        #expect(camelCase("my.model.v2") == "myModelV2")
    }

    @Test("Underscore-separated words become camelCase")
    func underscoreSeparated() {
        #expect(camelCase("my_model_name") == "myModelName")
    }

    @Test("Mixed separators produce correct camelCase")
    func mixedSeparators() {
        #expect(camelCase("model-name_v1.0") == "modelNameV10")
    }

    @Test("Already lowercase single token stays lowercase")
    func alreadyLowercase() {
        #expect(camelCase("model") == "model")
    }

    @Test("All-uppercase word is fully lowercased as first component")
    func allUppercaseFirst() {
        #expect(camelCase("MODEL") == "model")
    }

    @Test("Empty string returns empty string")
    func emptyString() {
        #expect(camelCase("") == "")
    }

    @Test("String of only separators returns empty string")
    func onlySeparators() {
        #expect(camelCase("---") == "")
    }

    @Test("Numbers are preserved in position")
    func numbersPreserved() {
        // The tool lowercases the first component, so "3B" → "3b"
        #expect(camelCase("3B-model") == "3bModel")
    }
}

// MARK: - ModelSource code-generation output tests

@Suite("GenerateModelSourcesTool – output generation")
struct ModelSourceGenerationTests {

    /// Reproduces the code-generation logic from main.swift so we can assert
    /// the shape of the generated Swift source without running the tool binary.
    private func generatedOutput(modelNames: [String]) -> String {
        let cases = modelNames
            .map { "    case \(camelCase($0)) = \"\($0)\"" }
            .joined(separator: "\n")

        return """
        // Auto-generated by GenerateModelSourcesTool — do not edit manually.
        import Foundation

        public enum ModelSourceError: Error {
            case modelNotFound(String)
        }

        public enum ModelSource: String, CaseIterable, ModelSourceable {
        \(cases)

            public func filePath() throws -> URL {
                guard let url = Bundle.module.url(forResource: rawValue, withExtension: nil, subdirectory: "Models") else {
                    throw ModelSourceError.modelNotFound(rawValue)
                }
                return url
            }

            public static var `default`: ModelSource? { allCases.first }
        }
        """
    }

    @Test("Output contains expected case for Llama model")
    func containsLlamaCase() {
        let output = generatedOutput(modelNames: ["Llama-3.2-3B-Instruct"])
        #expect(output.contains("case llama323BInstruct = \"Llama-3.2-3B-Instruct\""))
    }

    @Test("Output contains ModelSource enum declaration")
    func containsEnumDeclaration() {
        let output = generatedOutput(modelNames: ["SomeModel"])
        #expect(output.contains("public enum ModelSource"))
    }

    @Test("Output contains ModelSourceError declaration")
    func containsErrorDeclaration() {
        let output = generatedOutput(modelNames: [])
        #expect(output.contains("public enum ModelSourceError: Error"))
    }

    @Test("Output contains filePath() method")
    func containsFilePathMethod() {
        let output = generatedOutput(modelNames: [])
        #expect(output.contains("public func filePath() throws -> URL"))
    }

    @Test("Output contains default property")
    func containsDefaultProperty() {
        let output = generatedOutput(modelNames: [])
        #expect(output.contains("public static var `default`"))
    }

    @Test("Multiple models each get their own case")
    func multipleModels() {
        let output = generatedOutput(modelNames: ["Model-A", "Model-B"])
        #expect(output.contains("case modelA = \"Model-A\""))
        #expect(output.contains("case modelB = \"Model-B\""))
    }

    @Test("Empty model list produces no case lines")
    func emptyModels() {
        let output = generatedOutput(modelNames: [])
        // Generated model cases are always of the form:  case identifier = "RawValue"
        // ModelSourceError / CaseIterable never produce that pattern.
        let hasModelCase = output.range(of: #"case \w+ = ""#, options: .regularExpression) != nil
        #expect(!hasModelCase)
    }

    @Test("Auto-generated header is present")
    func headerPresent() {
        let output = generatedOutput(modelNames: [])
        #expect(output.contains("// Auto-generated by GenerateModelSourcesTool"))
    }
}
