import Foundation

public protocol ModelSourceable {
    func filePath() throws -> URL
}

// ModelSource enum cases are generated by the build plugin — see ModelSource+Generated.swift
// The enum itself is declared there.
