import Foundation

guard CommandLine.arguments.count == 3 else {
    fputs("Usage: GenerateModelSourcesTool <models-dir> <output-file>\n", stderr)
    exit(1)
}

let modelsDir = CommandLine.arguments[1]
let outputPath = CommandLine.arguments[2]

func camelCase(_ name: String) -> String {
    name
        .components(separatedBy: CharacterSet.alphanumerics.inverted)
        .filter { !$0.isEmpty }
        .enumerated()
        .map { $0.offset == 0 ? $0.element.lowercased() : $0.element.capitalized }
        .joined()
}

let modelNames = (try? FileManager.default.contentsOfDirectory(atPath: modelsDir))?
    .filter {
        var isDir: ObjCBool = false
        FileManager.default.fileExists(atPath: "\(modelsDir)/\($0)", isDirectory: &isDir)
        return isDir.boolValue
    }
    .sorted() ?? []

let cases = modelNames
    .map { "    case \(camelCase($0)) = \"\($0)\"" }
    .joined(separator: "\n")

let output = """
// Auto-generated by GenerateModelSourcesTool — do not edit manually.
import Foundation

public enum ModelSourceError: Error {
    case modelNotFound(String)
}

public enum ModelSource: String, CaseIterable, ModelSourceable {
\(cases)

    public func filePath() throws -> URL {
        guard let url = Bundle.module.url(forResource: rawValue, withExtension: nil, subdirectory: "Models") else {
            throw ModelSourceError.modelNotFound(rawValue)
        }
        return url
    }

    public static var `default`: ModelSource? { allCases.first }
}
"""

try output.write(toFile: outputPath, atomically: true, encoding: .utf8)
print("Generated \(modelNames.count) model(s) → \(outputPath)")
